### ISSUE TITLE
Padronizar icones, botões e mensagens no sistema

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#1111]
Padronizar:
- [ ] icones de botões
  - utilizar de acordo com a ação proposta
- [ ] semântica de cores
  - btn-primary (ações de salvar)
  - btn-warning (ações de edição)
  - btn-info (ações auxiliares)
  - btn-danger (ações de exclusão)
- [ ] mensagens de erro, alerta e sucesso
  - usar https://github.com/CodeSeven/toastr para as notificações

**Comment by lukasqw** [comment]
Alterações WEB:
- log.php
- mesas.php
- mapa.php
- grade.php
- perfis.php
 - rodape.php
- caixas.php
- vendas.php
- contas.php
- rel_dre.php
- clientes.php
- extrato.php
- estoque.php
- operacao.php
- fabricantes.php
- categorias.php
- maquinetas.php
- depositos.php
- dashboard.php
 -devolucao.php
- inventario.php
- produtos.php
- rel_sangria.php
- rel_caixas.php
- zoneamento.php
- regra_servico.php
- ordem-servico.php
- fornecedores.php
- controle_nfe.php
- importadores.php
- lancamentos.php
- regra_tributos.php
- situacao_especial.php
- procedimentos.php
- plano_contas.php
- zera-estoque.php
- baixa_estoque.php
- faixa_desconto.php
- base_tributaria.php
- controle-mesas.php
- desejos_clientes.php
- rel_curvas_abc.php
- grupo_comissao.php
 - ordem_producao.php
- posicao_estoque.php
- regime_especial.php
- rel_contas_pagar.php
- rel_vendas_deposito.php
- rel_pagamentos.php
-rel_vendas_periodo.php
- rel_aniversariantes.php
- especializacao_ncm.php
- relatorio-vendas-mesa.php
- rel_vendas_produto.php
- rel-vendas-categoria.php
- pedido_transferencia.php
- rel_analitico_estoque.php
- rel_periodo_vendedor.php
- pedidos_fornecedores.php
- rel_vendas_fabricante.php
- rel_produtos_vencer.php
- rel_produtos_vencidos.php
- rel_consolidado_caixa.php
- rel_fechamento_mensal.php
- empreendimento_config.php
- rel_pagamentos_fornecedor.php
- rel_movimentacao_caixa.php
- rel_total_produto_estoque.php
- faixa_desconto_permitido.php
- rel_saldo_devedor_cliente.php
- rel-movimentacao-estoque.php
- rel_total_vendas_cliente.php
- rel_total_vendas_vendedor.php
- rel_vendas_hora_a_hora.php
- rel_vendas_produto_mes.php
- planejamento_plano_contas.php
- rel_vendas_vendedor_dia_dia.php
- rel_produtos_estoque_minimo.php
- relatorio-consolidado-caixa-bordero.php
- rel_movimentacao_caixa_periodo.php
- pedido_transferencia_recebido.php
- toastr/toastr.css
- toastr/toastr.js.map
- toastr/toastr.min.css
- toastr/toastr.min.js
- js/angular-controller/mesas-controller.js
- js/angular-controller/mapa-controller.js
- js/angular-controller/perfis-controller.js
- js/angular-controller/grade-controller.js
- js/angular-controller/caixas-controller.js
- js/angular-controller/contas-controller.js
- js/angular-controller/extrato-controller.js
- js/angular-controller/clientes-controller.js
- js/angular-controller/estoque-controller.js
- js/angular-controller/operacao-controller.js
- js/angular-controller/inventario-controller.js
- js/angular-controller/maquinetas-controller.js
- js/angular-controller/produtos-controller.js
- js/angular-controller/depositos-controller.js
- js/angular-controller/categorias-controller.js
- js/angular-controller/dashboard-controller.js
- js/angular-controller/devolucao-controller.js
-s/angular-controller/zera-estoque-controller.js
- js/angular-controller/regra_servico-controller.js
- js/angular-controller/fabricantes-controller.js
- js/angular-controller/zoneamento-controller.js
- js/angular-controller/plano_contas-controller.js
- js/angular-controller/lancamentos-controller.js
- js/angular-controller/importadores-controller.js
- js/angular-controller/controle_nfe-controller.js
- js/angular-controller/regra_tributos-controller.js
- js/angular-controller/baixa_estoque-controller.js
- js/angular-controller/base_tributaria-controller.js
- js/angular-controller/faixa-desconto-controller.js
- js/angular-controller/ordem_servico-controller.js
- js/angular-controller/regime_especial-controller.js
- js/angular-controller/procedimentos-controller.js
- js/angular-controller/desejos_clientes-controller.js
- js/angular-controller/situacao_especial-controller.js
- js/angular-controller/ordem_producao-controller.js
- js/angular-controller/posicao_estoque-controller.js
- js/angular-controller/especializacao_ncm-controller.js
- js/angular-controller/pedido_transferencia-controller.js
- js/angular-controller/empreendimento_config-controller.js
- js/angular-controller/faixa_desconto_permitido-controller.js
- js/angular-controller/grupo-comissao-vendedor-controller.js
- js/angular-controller/planejamento_plano_contas-controller.js
- js/angular-controller/pedido_transferencia_recebido-controller.js

**Comment by Kenzo13** [comment]
- Tela de Regime especial    (configurações) está com o padrão antigo
- Tela de Regra de serviço    (configurações) está com os botões pequenos

**Comment by LEANDROCOELHO84** [comment]
situacao_especial.php

modal pesquisa de produtos não retorna produtos pesquisados.

**Comment by LEANDROCOELHO84** [comment]
regra_servico.php - 

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/homologacaoerp/public_html/regra_servico.php:1) in /home/homologacaoerp/public_html/util/login/restrito.php on line 3

**Comment by LEANDROCOELHO84** [comment]
faixa_desconto.php

não esta selecionando botoes de cores não podendo salvar nova faixa de desconto

**Comment by LEANDROCOELHO84** [comment]
controle-mesas.php

controle de mesas não esta abrindo comandas 
{"message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_tipo_conta_posi' in 'field list'","File":"\/home\/homologacaoerp\/public_html\/api\/util\/Conexao\/Conexao.php","line":109}

**Comment by LEANDROCOELHO84** [comment]
grupo_comissao.php

não é possi deletar faixa grupo de comissão

500 Internal Server Error
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`weblinia_clientes`.`tbl_vendas`, CONSTRAINT `fk_clientes_tb_vendas_tb_usuarios` FOREIGN KEY (`id_cliente`) REFERENCES `tbl_usuarios` (`id`)) (23000)


#0 /home/homologacaoerp/public_html/api/dao/GrupoComissaoVendedorDao.php(95): PDOStatement->execute()
#1 /home/homologacaoerp/public_html/api/controller/GrupoComissaoVendedorController.php(111): GrupoComissaoVendedorDao->deleteGrupoComissaoVendedor('39')
