### ISSUE TITLE
Possibilidade de busca do cliente no painel principal das mesas

### ISSUE THREAD

**Issue by filipecoelho** [WebliniaERP/webliniaerp-web#843]

**Comment by rafaelqw** [comment]
Alterações WEB:
- controle-mesas.php
- js/angular-controller/controle-mesas_controller.js

Alterações API:
- controller/MesaController.php
- dao/MesaDao.php
- index.php

**Comment by LEANDROCOELHO84** [comment]
ao consultar pesquisa avançada no controle de mesa ocorreu um erro  não ocorrendo a pesquisa do cliente

```
500 Internal Server Error
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cliente' in 'where clause' (42S22)
#0 /home/webliniaerp/public_html/api/util/Conexao/Conexao.php(234): PDOStatement->execute()
#1 /home/webliniaerp/public_html/api/dao/MesaDao.php(158): Conexao->select('SELECT \n\t\t\t\ttv....', true)
#2 /home/webliniaerp/public_html/api/controller/MesaController.php(79): MesaDao->getComandasByMesa('cliente')
#3 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(193): MesaController::getComandasByMesa('cliente')
#4 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /home/webliniaerp/public_html/api/util/flight/Engine.php(303): flight\core\Dispatcher::execute(Array, Array)
#6 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(188): flight\Engine->_start()
#7 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#9 /home/webliniaerp/public_html/api/util/flight/Engine.php(63): flight\core\Dispatcher->run('start', Array)
#10 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(188): flight\Engine->__call('start', Array)
#11 /home/webliniaerp/public_html/api/util/flight/core/Dispatcher.php(188): flight\Engine->start()
#12 /home/webliniaerp/public_html/api/util/flight/Flight.php(43): flight\core\Dispatcher::invokeMethod(Array, Array)
#13 /home/webliniaerp/public_html/api/index.php(776): Flight::__callStatic('start', Array)
#14 /home/webliniaerp/public_html/api/index.php(776): Flight::start()
#15 {main}
```
